#!/usr/bin/env bash
PATH="/usr/local/bin:$PATH"

echo "Running static analysis..."

# Validate Kotlin code with detekt and KtLint before committing
mvn detekt:check@detekt-custom


status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no issues. Proceeding with commit."
    exit 0
else
    echo 1>&2 "Static analysis found issues you need to fix before committing."
    exit 1
fi